// src/lib/combat/moves.ts
// Complete move pool — ALL moves from the real game. Both fighters share this pool.

import { Position, MoveType, MoveRarity, type Move } from "./types";

/**
 * Every move in the game, across all 19 positions.
 * Both the player and opponent draw from this same pool.
 * Rarities match the game's MOVE_RARITIES dictionary exactly.
 */
export const ALL_MOVES: Move[] = [
  // ═══════════════════════════════════════════
  // STANDING
  // ═══════════════════════════════════════════
  {
    id: "single_leg",
    name: "Single Leg",
    past_tense: "hit a Single Leg",
    type: MoveType.ATK,
    stat: "wrestling",
    base_chance: 0.40,
    points: 2,
    from_position: Position.STANDING,
    success_position: Position.GUARD_TOP,
    fail_position: Position.STANDING,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "wrestle",
    name: "Shoot Double Leg",
    past_tense: "hit a Double Leg",
    type: MoveType.ATK,
    stat: "wrestling",
    base_chance: 0.50,
    points: 2,
    from_position: Position.STANDING,
    success_position: Position.GUARD_TOP,
    fail_position: Position.STANDING,
    rarity: MoveRarity.RARE,
  },
  {
    id: "pull_guard",
    name: "Pull Guard",
    past_tense: "Pulled Guard",
    type: MoveType.TRN,
    stat: "guard",
    base_chance: 0.60,
    points: 0,
    from_position: Position.STANDING,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.STANDING,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "snapdown",
    name: "Snapdown",
    past_tense: "hit a Snapdown",
    type: MoveType.TRN,
    stat: "wrestling",
    base_chance: 0.40,
    points: 0,
    from_position: Position.STANDING,
    success_position: Position.FRONT_HEADLOCK_ATTACK,
    fail_position: Position.STANDING,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "throw",
    name: "Hip Throw",
    past_tense: "hit a Hip Throw",
    type: MoveType.ATK,
    stat: "wrestling",
    base_chance: 0.45,
    points: 3,
    from_position: Position.STANDING,
    success_position: Position.SIDE_CONTROL_TOP,
    fail_position: Position.STANDING,
    rarity: MoveRarity.EPIC,
  },
  {
    id: "knee_tap",
    name: "Knee Tap",
    past_tense: "hit a Knee Tap",
    type: MoveType.ATK,
    stat: "wrestling",
    base_chance: 0.50,
    points: 2,
    from_position: Position.STANDING,
    success_position: Position.HALF_GUARD_TOP,
    fail_position: Position.STANDING,
    rarity: MoveRarity.RARE,
  },
  {
    id: "arm_drag",
    name: "Arm Drag",
    past_tense: "hit an Arm Drag",
    type: MoveType.ATK,
    stat: "wrestling",
    base_chance: 0.60,
    points: 3,
    from_position: Position.STANDING,
    success_position: Position.TURTLE_TOP,
    fail_position: Position.STANDING,
    rarity: MoveRarity.LEGENDARY,
  },
  {
    id: "footsweep_snapdown",
    name: "Footsweep Snapdown",
    past_tense: "hit a Footsweep Snapdown",
    type: MoveType.TRN,
    stat: "wrestling",
    base_chance: 0.60,
    points: 0,
    from_position: Position.STANDING,
    success_position: Position.FRONT_HEADLOCK_ATTACK,
    fail_position: Position.STANDING,
    rarity: MoveRarity.COMMON,
  },

  // ═══════════════════════════════════════════
  // GUARD BOTTOM
  // ═══════════════════════════════════════════
  {
    id: "triangle",
    name: "Triangle Choke",
    past_tense: "locked up a Triangle",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.30,
    points: 0,
    sub_chance: 0.50,
    from_position: Position.GUARD_BOTTOM,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.HALF_GUARD_BOTTOM,
    rarity: MoveRarity.EPIC,
  },
  {
    id: "armbar_guard",
    name: "Armbar",
    past_tense: "caught an Armbar",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.25,
    points: 0,
    sub_chance: 0.45,
    from_position: Position.GUARD_BOTTOM,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.GUARD_BOTTOM,
    rarity: MoveRarity.RARE,
  },
  {
    id: "sweep",
    name: "Hip Bump Sweep",
    past_tense: "hit a Hip Bump Sweep",
    type: MoveType.ATK,
    stat: "guard",
    base_chance: 0.40,
    points: 2,
    from_position: Position.GUARD_BOTTOM,
    success_position: Position.MOUNT_TOP,
    fail_position: Position.GUARD_BOTTOM,
    rarity: MoveRarity.RARE,
  },
  {
    id: "lumberjack_sweep",
    name: "Lumberjack Sweep",
    past_tense: "hit a Lumberjack Sweep",
    type: MoveType.ATK,
    stat: "guard",
    base_chance: 0.35,
    points: 2,
    from_position: Position.GUARD_BOTTOM,
    success_position: Position.GUARD_TOP,
    fail_position: Position.GUARD_BOTTOM,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "stand_up",
    name: "Stand Up",
    past_tense: "Stood Up",
    type: MoveType.TRN,
    stat: "cardio",
    base_chance: 0.50,
    points: 0,
    from_position: Position.GUARD_BOTTOM,
    success_position: Position.STANDING,
    fail_position: Position.GUARD_BOTTOM,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "heist_snapdown",
    name: "Heist and Snapdown",
    past_tense: "hit a Heist and Snapdown",
    type: MoveType.TRN,
    stat: "wrestling",
    base_chance: 0.65,
    points: 0,
    from_position: Position.GUARD_BOTTOM,
    success_position: Position.FRONT_HEADLOCK_ATTACK,
    fail_position: Position.GUARD_BOTTOM,
    rarity: MoveRarity.COMMON,
  },

  // ═══════════════════════════════════════════
  // GUARD TOP
  // ═══════════════════════════════════════════
  {
    id: "force_half_guard",
    name: "Force Half Guard",
    past_tense: "Forced Half Guard",
    type: MoveType.ATK,
    stat: "passing",
    base_chance: 0.65,
    points: 0,
    from_position: Position.GUARD_TOP,
    success_position: Position.HALF_GUARD_TOP,
    fail_position: Position.GUARD_TOP,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "knee_slice_pass",
    name: "Knee Slice",
    past_tense: "hit a Knee Slice Pass",
    type: MoveType.ATK,
    stat: "passing",
    base_chance: 0.50,
    points: 3,
    from_position: Position.GUARD_TOP,
    success_position: Position.SIDE_CONTROL_TOP,
    fail_position: Position.GUARD_TOP,
    rarity: MoveRarity.EPIC,
  },
  {
    id: "double_under_pass",
    name: "Double Under Pass",
    past_tense: "hit a Double Under Pass",
    type: MoveType.ATK,
    stat: "strength",
    base_chance: 0.35,
    points: 3,
    from_position: Position.GUARD_TOP,
    success_position: Position.SIDE_CONTROL_TOP,
    fail_position: Position.HALF_GUARD_TOP,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "torreando_pass",
    name: "Torreando Pass",
    past_tense: "hit a Torreando Pass",
    type: MoveType.ATK,
    stat: "passing",
    base_chance: 0.60,
    points: 3,
    from_position: Position.GUARD_TOP,
    success_position: Position.SIDE_CONTROL_TOP,
    fail_position: Position.GUARD_TOP,
    rarity: MoveRarity.LEGENDARY,
  },
  {
    id: "fallback_to_slx",
    name: "Fall Back to Single Leg X",
    past_tense: "fell back to Single Leg X",
    type: MoveType.TRN,
    stat: "guard",
    base_chance: 0.75,
    points: 0,
    from_position: Position.GUARD_TOP,
    success_position: Position.SINGLE_LEG_X_OFFENSE,
    fail_position: Position.GUARD_TOP,
    rarity: MoveRarity.RARE,
  },

  // ═══════════════════════════════════════════
  // HALF GUARD BOTTOM
  // ═══════════════════════════════════════════
  {
    id: "underhook_sweep",
    name: "Underhook Sweep",
    past_tense: "hit an Underhook Sweep",
    type: MoveType.ATK,
    stat: "guard",
    base_chance: 0.40,
    points: 2,
    from_position: Position.HALF_GUARD_BOTTOM,
    success_position: Position.GUARD_TOP,
    fail_position: Position.HALF_GUARD_BOTTOM,
    rarity: MoveRarity.RARE,
  },
  {
    id: "recover_guard",
    name: "Recover Full Guard",
    past_tense: "Recovered Full Guard",
    type: MoveType.TRN,
    stat: "guard",
    base_chance: 0.55,
    points: 0,
    from_position: Position.HALF_GUARD_BOTTOM,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.HALF_GUARD_BOTTOM,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "enter_single_leg_x",
    name: "Enter Single Leg X",
    past_tense: "Entered Single Leg X",
    type: MoveType.TRN,
    stat: "guard",
    base_chance: 0.45,
    points: 0,
    from_position: Position.HALF_GUARD_BOTTOM,
    success_position: Position.SINGLE_LEG_X_OFFENSE,
    fail_position: Position.HALF_GUARD_BOTTOM,
    rarity: MoveRarity.RARE,
  },
  {
    id: "enter_saddle",
    name: "Enter Saddle",
    past_tense: "Entered the Saddle",
    type: MoveType.TRN,
    stat: "guard",
    base_chance: 0.45,
    points: 0,
    from_position: Position.HALF_GUARD_BOTTOM,
    success_position: Position.SADDLE_OFFENSE,
    fail_position: Position.HALF_GUARD_BOTTOM,
    rarity: MoveRarity.EPIC,
  },
  {
    id: "octopus_guard_sweep",
    name: "Octopus Guard Sweep",
    past_tense: "hit an Octopus Guard Sweep",
    type: MoveType.ATK,
    stat: "guard",
    base_chance: 0.55,
    points: 2,
    from_position: Position.HALF_GUARD_BOTTOM,
    success_position: Position.HALF_GUARD_TOP,
    fail_position: Position.HALF_GUARD_BOTTOM,
    rarity: MoveRarity.LEGENDARY,
  },

  // ═══════════════════════════════════════════
  // HALF GUARD TOP
  // ═══════════════════════════════════════════
  {
    id: "pummel_pass",
    name: "Pummel Leg Out to Pass",
    past_tense: "Pummeled Leg Out to Pass",
    type: MoveType.ATK,
    stat: "passing",
    base_chance: 0.45,
    points: 3,
    from_position: Position.HALF_GUARD_TOP,
    success_position: Position.SIDE_CONTROL_TOP,
    fail_position: Position.HALF_GUARD_TOP,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "pass_to_side",
    name: "Crossface and Pressure Pass",
    past_tense: "hit a Crossface and Pressure Pass",
    type: MoveType.ATK,
    stat: "passing",
    base_chance: 0.50,
    points: 3,
    from_position: Position.HALF_GUARD_TOP,
    success_position: Position.SIDE_CONTROL_TOP,
    fail_position: Position.HALF_GUARD_TOP,
    rarity: MoveRarity.EPIC,
  },
  {
    id: "kimura_half",
    name: "Kimura",
    past_tense: "locked up a Kimura",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.30,
    points: 0,
    sub_chance: 0.30,
    from_position: Position.HALF_GUARD_TOP,
    success_position: Position.HALF_GUARD_TOP,
    fail_position: Position.GUARD_TOP,
    rarity: MoveRarity.RARE,
  },
  {
    id: "backstep_to_saddle",
    name: "Backstep to Saddle",
    past_tense: "Backstepped to Saddle",
    type: MoveType.TRN,
    stat: "leg_entanglements",
    base_chance: 0.45,
    points: 0,
    from_position: Position.HALF_GUARD_TOP,
    success_position: Position.SADDLE_OFFENSE,
    fail_position: Position.HALF_GUARD_BOTTOM,
    rarity: MoveRarity.EPIC,
  },

  // ═══════════════════════════════════════════
  // SIDE CONTROL TOP
  // ═══════════════════════════════════════════
  {
    id: "throw_leg_mount",
    name: "Throw Leg Over to Mount",
    past_tense: "Threw Leg Over to Mount",
    type: MoveType.ATK,
    stat: "passing",
    base_chance: 0.35,
    points: 4,
    from_position: Position.SIDE_CONTROL_TOP,
    success_position: Position.MOUNT_TOP,
    fail_position: Position.HALF_GUARD_TOP,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "mount_transition",
    name: "KoB to Mount",
    past_tense: "Used Knee on Belly to get to Mount",
    type: MoveType.ATK,
    stat: "passing",
    base_chance: 0.50,
    points: 4,
    from_position: Position.SIDE_CONTROL_TOP,
    success_position: Position.MOUNT_TOP,
    fail_position: Position.HALF_GUARD_TOP,
    rarity: MoveRarity.EPIC,
  },
  {
    id: "kimura_side",
    name: "Kimura",
    past_tense: "locked up a Kimura",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.35,
    points: 0,
    sub_chance: 0.35,
    from_position: Position.SIDE_CONTROL_TOP,
    success_position: Position.SIDE_CONTROL_TOP,
    fail_position: Position.SIDE_CONTROL_TOP,
    rarity: MoveRarity.RARE,
  },
  {
    id: "take_back_side",
    name: "Expose Back and Throw in Hooks",
    past_tense: "Exposed the Back and Threw in Hooks",
    type: MoveType.ATK,
    stat: "passing",
    base_chance: 0.35,
    points: 4,
    from_position: Position.SIDE_CONTROL_TOP,
    success_position: Position.BACK_CONTROL,
    fail_position: Position.SIDE_CONTROL_TOP,
    rarity: MoveRarity.LEGENDARY,
  },

  // ═══════════════════════════════════════════
  // SIDE CONTROL BOTTOM
  // ═══════════════════════════════════════════
  {
    id: "escape_to_guard",
    name: "Hip Escape to Guard",
    past_tense: "Escaped to Guard",
    type: MoveType.DEF,
    stat: "escapes",
    base_chance: 0.45,
    points: 0,
    from_position: Position.SIDE_CONTROL_BOTTOM,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.SIDE_CONTROL_BOTTOM,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "turtle_up_side_control",
    name: "Turtle Up",
    past_tense: "Turtled Up",
    type: MoveType.DEF,
    stat: "strength",
    base_chance: 0.60,
    points: 0,
    from_position: Position.SIDE_CONTROL_BOTTOM,
    success_position: Position.TURTLE_BOTTOM,
    fail_position: Position.SIDE_CONTROL_BOTTOM,
    rarity: MoveRarity.RARE,
  },
  {
    id: "frame_defense",
    name: "Frame and Stall",
    past_tense: "Framed and Stalled",
    type: MoveType.DEF,
    stat: "cardio",
    base_chance: 0.70,
    points: 0,
    from_position: Position.SIDE_CONTROL_BOTTOM,
    success_position: Position.SIDE_CONTROL_BOTTOM,
    fail_position: Position.SIDE_CONTROL_BOTTOM,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "buggy_choke",
    name: "Buggy Choke",
    past_tense: "locked up a Buggy Choke",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.30,
    points: 0,
    sub_chance: 0.45,
    from_position: Position.SIDE_CONTROL_BOTTOM,
    success_position: Position.SIDE_CONTROL_BOTTOM,
    fail_position: Position.SIDE_CONTROL_BOTTOM,
    rarity: MoveRarity.EPIC,
  },

  // ═══════════════════════════════════════════
  // MOUNT TOP
  // ═══════════════════════════════════════════
  {
    id: "maintain_mount",
    name: "Apply Pressure",
    past_tense: "Applied Pressure and Maintained Mount",
    type: MoveType.DEF,
    stat: "passing",
    base_chance: 0.65,
    points: 0,
    from_position: Position.MOUNT_TOP,
    success_position: Position.MOUNT_TOP,
    fail_position: Position.MOUNT_TOP,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "head_arm_choke",
    name: "Head and Arm Choke",
    past_tense: "locked up a Head and Arm Choke",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.30,
    points: 0,
    sub_chance: 0.35,
    from_position: Position.MOUNT_TOP,
    success_position: Position.MOUNT_TOP,
    fail_position: Position.SIDE_CONTROL_TOP,
    rarity: MoveRarity.RARE,
  },
  {
    id: "armbar_mount",
    name: "Armbar",
    past_tense: "caught an Armbar",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.40,
    points: 0,
    sub_chance: 0.50,
    from_position: Position.MOUNT_TOP,
    success_position: Position.MOUNT_TOP,
    fail_position: Position.GUARD_TOP,
    rarity: MoveRarity.EPIC,
  },
  {
    id: "smother_choke",
    name: "Smother Choke",
    past_tense: "locked in a Smother Choke",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.35,
    points: 0,
    sub_chance: 0.35,
    from_position: Position.MOUNT_TOP,
    success_position: Position.MOUNT_TOP,
    fail_position: Position.MOUNT_TOP,
    rarity: MoveRarity.RARE,
  },
  {
    id: "take_back_mount",
    name: "Gift Wrap Back Take",
    past_tense: "hit a Gift Wrap Back Take",
    type: MoveType.ATK,
    stat: "passing",
    base_chance: 0.50,
    points: 4,
    from_position: Position.MOUNT_TOP,
    success_position: Position.BACK_CONTROL,
    fail_position: Position.SIDE_CONTROL_TOP,
    rarity: MoveRarity.LEGENDARY,
  },

  // ═══════════════════════════════════════════
  // MOUNT BOTTOM
  // ═══════════════════════════════════════════
  {
    id: "upa",
    name: "Trap & Roll (Upa)",
    past_tense: "hit a Trap & Roll",
    type: MoveType.DEF,
    stat: "escapes",
    base_chance: 0.40,
    points: 2,
    from_position: Position.MOUNT_BOTTOM,
    success_position: Position.GUARD_TOP,
    fail_position: Position.MOUNT_BOTTOM,
    rarity: MoveRarity.RARE,
  },
  {
    id: "elbow_escape",
    name: "Elbow Escape to Half Guard",
    past_tense: "Escaped to Half Guard",
    type: MoveType.DEF,
    stat: "escapes",
    base_chance: 0.45,
    points: 0,
    from_position: Position.MOUNT_BOTTOM,
    success_position: Position.HALF_GUARD_BOTTOM,
    fail_position: Position.MOUNT_BOTTOM,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "survive_mount",
    name: "Protect & Survive",
    past_tense: "Survived",
    type: MoveType.DEF,
    stat: "cardio",
    base_chance: 0.65,
    points: 0,
    from_position: Position.MOUNT_BOTTOM,
    success_position: Position.MOUNT_BOTTOM,
    fail_position: Position.MOUNT_BOTTOM,
    rarity: MoveRarity.COMMON,
  },

  // ═══════════════════════════════════════════
  // BACK CONTROL
  // ═══════════════════════════════════════════
  {
    id: "rnc",
    name: "Rear Naked Choke",
    past_tense: "locked in a Rear Naked Choke",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.45,
    points: 0,
    sub_chance: 0.55,
    from_position: Position.BACK_CONTROL,
    success_position: Position.BACK_CONTROL,
    fail_position: Position.BACK_CONTROL,
    rarity: MoveRarity.LEGENDARY,
  },
  {
    id: "armbar_back",
    name: "Armbar from Back",
    past_tense: "caught an Armbar from Back",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.30,
    points: 0,
    sub_chance: 0.45,
    from_position: Position.BACK_CONTROL,
    success_position: Position.BACK_CONTROL,
    fail_position: Position.BACK_CONTROL,
    rarity: MoveRarity.RARE,
  },
  {
    id: "mount_from_back",
    name: "Transition to Mount",
    past_tense: "Transitioned to Mount",
    type: MoveType.ATK,
    stat: "passing",
    base_chance: 0.40,
    points: 3,
    from_position: Position.BACK_CONTROL,
    success_position: Position.MOUNT_TOP,
    fail_position: Position.SIDE_CONTROL_TOP,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "twister",
    name: "Twister",
    past_tense: "locked in a Twister",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.35,
    points: 0,
    sub_chance: 0.50,
    from_position: Position.BACK_CONTROL,
    success_position: Position.BACK_CONTROL,
    fail_position: Position.BACK_CONTROL,
    rarity: MoveRarity.EPIC,
  },

  // ═══════════════════════════════════════════
  // BACK EXPOSED
  // ═══════════════════════════════════════════
  {
    id: "clear_hooks",
    name: "Clear Hooks and Get to Guard",
    past_tense: "Cleared the Hooks and Got to Guard",
    type: MoveType.DEF,
    stat: "escapes",
    base_chance: 0.40,
    points: 0,
    from_position: Position.BACK_EXPOSED,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.BACK_EXPOSED,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "turtle_up",
    name: "Clear One Hook and Turtle Up",
    past_tense: "Cleared One Hook and Turtled Up",
    type: MoveType.DEF,
    stat: "cardio",
    base_chance: 0.50,
    points: 0,
    from_position: Position.BACK_EXPOSED,
    success_position: Position.TURTLE_BOTTOM,
    fail_position: Position.BACK_EXPOSED,
    rarity: MoveRarity.RARE,
  },
  {
    id: "hand_fight",
    name: "Hand Fight Defense",
    past_tense: "Fought the Hands",
    type: MoveType.DEF,
    stat: "escapes",
    base_chance: 0.60,
    points: 0,
    from_position: Position.BACK_EXPOSED,
    success_position: Position.BACK_EXPOSED,
    fail_position: Position.BACK_EXPOSED,
    rarity: MoveRarity.COMMON,
  },

  // ═══════════════════════════════════════════
  // TURTLE TOP
  // ═══════════════════════════════════════════
  {
    id: "hooks_aggressive",
    name: "Throw in Hooks Aggressively",
    past_tense: "Threw in Hooks Aggressively",
    type: MoveType.ATK,
    stat: "wrestling",
    base_chance: 0.35,
    points: 4,
    from_position: Position.TURTLE_TOP,
    success_position: Position.BACK_CONTROL,
    fail_position: Position.TURTLE_TOP,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "take_back_turtle",
    name: "Power Half Back Take",
    past_tense: "Used Power Half to Take the Back",
    type: MoveType.ATK,
    stat: "passing",
    base_chance: 0.45,
    points: 4,
    from_position: Position.TURTLE_TOP,
    success_position: Position.BACK_CONTROL,
    fail_position: Position.TURTLE_TOP,
    rarity: MoveRarity.EPIC,
  },
  {
    id: "bulldog_choke",
    name: "Bulldog Choke",
    past_tense: "locked in a Bulldog Choke",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.25,
    points: 0,
    sub_chance: 0.30,
    from_position: Position.TURTLE_TOP,
    success_position: Position.TURTLE_TOP,
    fail_position: Position.TURTLE_TOP,
    rarity: MoveRarity.RARE,
  },
  {
    id: "front_headlock_snap",
    name: "Transition to Front Headlock",
    past_tense: "Snapped Down to Front Headlock",
    type: MoveType.ATK,
    stat: "wrestling",
    base_chance: 0.40,
    points: 0,
    from_position: Position.TURTLE_TOP,
    success_position: Position.FRONT_HEADLOCK_ATTACK,
    fail_position: Position.TURTLE_TOP,
    rarity: MoveRarity.COMMON,
  },

  // ═══════════════════════════════════════════
  // TURTLE BOTTOM
  // ═══════════════════════════════════════════
  {
    id: "break_grips_stand",
    name: "Break Grips and Stand Up",
    past_tense: "Broke Grips and Stood Up",
    type: MoveType.TRN,
    stat: "escapes",
    base_chance: 0.40,
    points: 0,
    from_position: Position.TURTLE_BOTTOM,
    success_position: Position.STANDING,
    fail_position: Position.TURTLE_BOTTOM,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "break_grips_guard",
    name: "Break Grips and Sit to Guard",
    past_tense: "Broke Grips and Sat to Guard",
    type: MoveType.TRN,
    stat: "escapes",
    base_chance: 0.40,
    points: 0,
    from_position: Position.TURTLE_BOTTOM,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.TURTLE_BOTTOM,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "granby_roll",
    name: "Granby Roll",
    past_tense: "hit a Granby Roll",
    type: MoveType.DEF,
    stat: "wrestling",
    base_chance: 0.50,
    points: 0,
    from_position: Position.TURTLE_BOTTOM,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.TURTLE_BOTTOM,
    rarity: MoveRarity.RARE,
  },
  {
    id: "roll_to_saddle",
    name: "Roll to Saddle",
    past_tense: "Rolled to the Saddle",
    type: MoveType.TRN,
    stat: "leg_entanglements",
    base_chance: 0.35,
    points: 0,
    from_position: Position.TURTLE_BOTTOM,
    success_position: Position.SADDLE_OFFENSE,
    fail_position: Position.SIDE_CONTROL_BOTTOM,
    rarity: MoveRarity.EPIC,
  },

  // ═══════════════════════════════════════════
  // FRONT HEADLOCK ATTACK
  // ═══════════════════════════════════════════
  {
    id: "cow_catcher",
    name: "Cow Catcher",
    past_tense: "hit a Cow Catcher",
    type: MoveType.ATK,
    stat: "wrestling",
    base_chance: 0.40,
    points: 3,
    from_position: Position.FRONT_HEADLOCK_ATTACK,
    success_position: Position.SIDE_CONTROL_TOP,
    fail_position: Position.FRONT_HEADLOCK_ATTACK,
    rarity: MoveRarity.RARE,
  },
  {
    id: "go_behind",
    name: "Go Behind",
    past_tense: "Went Behind",
    type: MoveType.ATK,
    stat: "wrestling",
    base_chance: 0.50,
    points: 0,
    from_position: Position.FRONT_HEADLOCK_ATTACK,
    success_position: Position.TURTLE_TOP,
    fail_position: Position.FRONT_HEADLOCK_ATTACK,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "high_wrist_guillotine",
    name: "High Wrist Guillotine",
    past_tense: "locked in a Guillotine",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.40,
    points: 0,
    sub_chance: 0.45,
    from_position: Position.FRONT_HEADLOCK_ATTACK,
    success_position: Position.FRONT_HEADLOCK_ATTACK,
    fail_position: Position.GUARD_TOP,
    rarity: MoveRarity.EPIC,
  },
  {
    id: "darce_choke",
    name: "D'Arce Choke",
    past_tense: "locked in a D'Arce",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.30,
    points: 0,
    sub_chance: 0.35,
    from_position: Position.FRONT_HEADLOCK_ATTACK,
    success_position: Position.SIDE_CONTROL_TOP,
    fail_position: Position.FRONT_HEADLOCK_ATTACK,
    rarity: MoveRarity.RARE,
  },

  // ═══════════════════════════════════════════
  // FRONT HEADLOCK DEFEND
  // ═══════════════════════════════════════════
  {
    id: "pull_guard_headlock",
    name: "Pull Guard",
    past_tense: "Pulled Guard",
    type: MoveType.TRN,
    stat: "guard",
    base_chance: 0.40,
    points: 0,
    from_position: Position.FRONT_HEADLOCK_DEFEND,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.FRONT_HEADLOCK_DEFEND,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "handfight_stand",
    name: "Handfight and Stand Up",
    past_tense: "Handfought and Stood Up",
    type: MoveType.TRN,
    stat: "wrestling",
    base_chance: 0.40,
    points: 0,
    from_position: Position.FRONT_HEADLOCK_DEFEND,
    success_position: Position.STANDING,
    fail_position: Position.FRONT_HEADLOCK_DEFEND,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "peek_out",
    name: "Peek Out",
    past_tense: "Peeked Out",
    type: MoveType.DEF,
    stat: "escapes",
    base_chance: 0.45,
    points: 0,
    from_position: Position.FRONT_HEADLOCK_DEFEND,
    success_position: Position.GUARD_TOP,
    fail_position: Position.FRONT_HEADLOCK_DEFEND,
    rarity: MoveRarity.RARE,
  },
  {
    id: "sucker_drag",
    name: "Sucker Drag",
    past_tense: "hit a Sucker Drag",
    type: MoveType.TRN,
    stat: "escapes",
    base_chance: 0.50,
    points: 0,
    from_position: Position.FRONT_HEADLOCK_DEFEND,
    success_position: Position.TURTLE_TOP,
    fail_position: Position.FRONT_HEADLOCK_DEFEND,
    rarity: MoveRarity.EPIC,
  },

  // ═══════════════════════════════════════════
  // SINGLE LEG X OFFENSE
  // ═══════════════════════════════════════════
  {
    id: "slx_sweep",
    name: "Sweep",
    past_tense: "hit a Sweep",
    type: MoveType.ATK,
    stat: "leg_entanglements",
    base_chance: 0.40,
    points: 2,
    from_position: Position.SINGLE_LEG_X_OFFENSE,
    success_position: Position.GUARD_TOP,
    fail_position: Position.SINGLE_LEG_X_OFFENSE,
    rarity: MoveRarity.RARE,
  },
  {
    id: "slx_footlock",
    name: "Straight Footlock",
    past_tense: "locked in a Straight Footlock",
    type: MoveType.SUB,
    stat: "leg_entanglements",
    base_chance: 0.35,
    points: 0,
    sub_chance: 0.35,
    from_position: Position.SINGLE_LEG_X_OFFENSE,
    success_position: Position.SINGLE_LEG_X_OFFENSE,
    fail_position: Position.HALF_GUARD_BOTTOM,
    rarity: MoveRarity.RARE,
  },
  {
    id: "slx_outside_heelhook",
    name: "Outside Heelhook",
    past_tense: "locked in an Outside Heelhook",
    type: MoveType.SUB,
    stat: "leg_entanglements",
    base_chance: 0.30,
    points: 0,
    sub_chance: 0.50,
    from_position: Position.SINGLE_LEG_X_OFFENSE,
    success_position: Position.SINGLE_LEG_X_OFFENSE,
    fail_position: Position.HALF_GUARD_BOTTOM,
    rarity: MoveRarity.EPIC,
  },

  // ═══════════════════════════════════════════
  // SINGLE LEG X DEFENSE
  // ═══════════════════════════════════════════
  {
    id: "rip_leg_out",
    name: "Rip Leg Out Aggressively",
    past_tense: "Ripped the Leg Out",
    type: MoveType.DEF,
    stat: "strength",
    base_chance: 0.35,
    points: 0,
    from_position: Position.SINGLE_LEG_X_DEFENSE,
    success_position: Position.GUARD_TOP,
    fail_position: Position.SINGLE_LEG_X_DEFENSE,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "disentangle_step_out",
    name: "Disentangle and Step Out",
    past_tense: "Disentangled and Stepped Out",
    type: MoveType.DEF,
    stat: "escapes",
    base_chance: 0.50,
    points: 0,
    from_position: Position.SINGLE_LEG_X_DEFENSE,
    success_position: Position.GUARD_TOP,
    fail_position: Position.SINGLE_LEG_X_DEFENSE,
    rarity: MoveRarity.RARE,
  },
  {
    id: "strip_grip_pass",
    name: "Strip Grip and Pressure Pass",
    past_tense: "Stripped the Grip and Passed",
    type: MoveType.DEF,
    stat: "passing",
    base_chance: 0.45,
    points: 3,
    from_position: Position.SINGLE_LEG_X_DEFENSE,
    success_position: Position.SIDE_CONTROL_TOP,
    fail_position: Position.SINGLE_LEG_X_DEFENSE,
    rarity: MoveRarity.EPIC,
  },

  // ═══════════════════════════════════════════
  // SADDLE OFFENSE
  // ═══════════════════════════════════════════
  {
    id: "ankle_lock_secondary",
    name: "Ankle Lock on Secondary Leg",
    past_tense: "locked in an Ankle Lock on the Secondary Leg",
    type: MoveType.SUB,
    stat: "leg_entanglements",
    base_chance: 0.30,
    points: 0,
    sub_chance: 0.35,
    from_position: Position.SADDLE_OFFENSE,
    success_position: Position.SADDLE_OFFENSE,
    fail_position: Position.SADDLE_OFFENSE,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "saddle_inside_heelhook",
    name: "Inside Heelhook",
    past_tense: "locked in an Inside Heelhook",
    type: MoveType.SUB,
    stat: "leg_entanglements",
    base_chance: 0.40,
    points: 0,
    sub_chance: 0.45,
    from_position: Position.SADDLE_OFFENSE,
    success_position: Position.SADDLE_OFFENSE,
    fail_position: Position.HALF_GUARD_BOTTOM,
    rarity: MoveRarity.RARE,
  },
  {
    id: "saddle_pass_heelhook",
    name: "Pass Across and Outside Heelhook",
    past_tense: "locked in an Outside Heelhook",
    type: MoveType.SUB,
    stat: "leg_entanglements",
    base_chance: 0.40,
    points: 0,
    sub_chance: 0.55,
    from_position: Position.SADDLE_OFFENSE,
    success_position: Position.SADDLE_OFFENSE,
    fail_position: Position.GUARD_BOTTOM,
    rarity: MoveRarity.EPIC,
  },
  {
    id: "saddle_to_back",
    name: "Transition to the Back",
    past_tense: "Transitioned to the Back",
    type: MoveType.ATK,
    stat: "leg_entanglements",
    base_chance: 0.50,
    points: 4,
    from_position: Position.SADDLE_OFFENSE,
    success_position: Position.BACK_CONTROL,
    fail_position: Position.HALF_GUARD_BOTTOM,
    rarity: MoveRarity.LEGENDARY,
  },

  // ═══════════════════════════════════════════
  // SADDLE DEFENSE
  // ═══════════════════════════════════════════
  {
    id: "rip_leg_out_saddle",
    name: "Rip Leg Out Aggressively",
    past_tense: "Ripped the Leg Out",
    type: MoveType.DEF,
    stat: "strength",
    base_chance: 0.30,
    points: 0,
    from_position: Position.SADDLE_DEFENSE,
    success_position: Position.GUARD_TOP,
    fail_position: Position.SADDLE_DEFENSE,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "hide_heel_extract",
    name: "Hide the Heel and Extract Leg",
    past_tense: "Hid the Heel and Extracted",
    type: MoveType.DEF,
    stat: "escapes",
    base_chance: 0.50,
    points: 0,
    from_position: Position.SADDLE_DEFENSE,
    success_position: Position.GUARD_TOP,
    fail_position: Position.SADDLE_DEFENSE,
    rarity: MoveRarity.RARE,
  },
  {
    id: "counter_back_take",
    name: "Counter Back Take",
    past_tense: "hit a Counter Back Take",
    type: MoveType.ATK,
    stat: "escapes",
    base_chance: 0.35,
    points: 4,
    from_position: Position.SADDLE_DEFENSE,
    success_position: Position.BACK_CONTROL,
    fail_position: Position.SADDLE_DEFENSE,
    rarity: MoveRarity.EPIC,
  },
];
