// src/lib/combat/moves.ts
// Complete move pools for player and opponent fighters.

import { Position, MoveType, MoveRarity, type Move } from "./types";

// ─── Player Moves (~25, including 2–3 legendary) ───

export const PLAYER_MOVES: Move[] = [
  // === STANDING ===
  {
    id: "p_takedown",
    name: "Takedown",
    type: MoveType.ATK,
    stat: "wrestling",
    base_chance: 0.55,
    points: 2,
    from_position: Position.STANDING,
    success_position: Position.GUARD_TOP,
    fail_position: Position.STANDING,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "p_pull_guard",
    name: "Pull Guard",
    type: MoveType.TRN,
    stat: "guard",
    base_chance: 0.70,
    points: 0,
    from_position: Position.STANDING,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.STANDING,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "p_sprawl",
    name: "Sprawl",
    type: MoveType.DEF,
    stat: "wrestling",
    base_chance: 0.65,
    points: 0,
    from_position: Position.STANDING,
    success_position: Position.FRONT_HEADLOCK_ATTACK,
    fail_position: Position.STANDING,
    rarity: MoveRarity.COMMON,
  },

  // === GUARD TOP ===
  {
    id: "p_guard_pass",
    name: "Guard Pass",
    type: MoveType.ATK,
    stat: "passing",
    base_chance: 0.45,
    points: 3,
    from_position: Position.GUARD_TOP,
    success_position: Position.SIDE_CONTROL_TOP,
    fail_position: Position.GUARD_TOP,
    rarity: MoveRarity.UNCOMMON,
  },
  {
    id: "p_stack_pass",
    name: "Stack Pass",
    type: MoveType.ATK,
    stat: "strength",
    base_chance: 0.50,
    points: 3,
    from_position: Position.GUARD_TOP,
    success_position: Position.HALF_GUARD_TOP,
    fail_position: Position.GUARD_TOP,
    rarity: MoveRarity.COMMON,
  },

  // === GUARD BOTTOM ===
  {
    id: "p_triangle",
    name: "Triangle",
    type: MoveType.SUB,
    stat: "guard",
    base_chance: 0.50,
    points: 0,
    from_position: Position.GUARD_BOTTOM,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.GUARD_BOTTOM,
    rarity: MoveRarity.UNCOMMON,
    sub_chance: 0.35,
  },
  {
    id: "p_armbar_guard",
    name: "Armbar",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.45,
    points: 0,
    from_position: Position.GUARD_BOTTOM,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.HALF_GUARD_BOTTOM,
    rarity: MoveRarity.RARE,
    sub_chance: 0.40,
  },
  {
    id: "p_hip_bump_sweep",
    name: "Hip Bump Sweep",
    type: MoveType.ATK,
    stat: "guard",
    base_chance: 0.50,
    points: 2,
    from_position: Position.GUARD_BOTTOM,
    success_position: Position.MOUNT_TOP,
    fail_position: Position.GUARD_BOTTOM,
    rarity: MoveRarity.UNCOMMON,
  },

  // === HALF GUARD TOP ===
  {
    id: "p_half_pass",
    name: "Knee Slide Pass",
    type: MoveType.ATK,
    stat: "passing",
    base_chance: 0.55,
    points: 3,
    from_position: Position.HALF_GUARD_TOP,
    success_position: Position.SIDE_CONTROL_TOP,
    fail_position: Position.HALF_GUARD_TOP,
    rarity: MoveRarity.COMMON,
  },

  // === HALF GUARD BOTTOM ===
  {
    id: "p_half_sweep",
    name: "Dogfight Sweep",
    type: MoveType.ATK,
    stat: "guard",
    base_chance: 0.45,
    points: 2,
    from_position: Position.HALF_GUARD_BOTTOM,
    success_position: Position.HALF_GUARD_TOP,
    fail_position: Position.HALF_GUARD_BOTTOM,
    rarity: MoveRarity.UNCOMMON,
  },
  {
    id: "p_half_recover",
    name: "Recover Full Guard",
    type: MoveType.DEF,
    stat: "guard",
    base_chance: 0.60,
    points: 0,
    from_position: Position.HALF_GUARD_BOTTOM,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.HALF_GUARD_BOTTOM,
    rarity: MoveRarity.COMMON,
  },

  // === SIDE CONTROL TOP ===
  {
    id: "p_mount_transition",
    name: "Advance to Mount",
    type: MoveType.TRN,
    stat: "passing",
    base_chance: 0.50,
    points: 4,
    from_position: Position.SIDE_CONTROL_TOP,
    success_position: Position.MOUNT_TOP,
    fail_position: Position.SIDE_CONTROL_TOP,
    rarity: MoveRarity.UNCOMMON,
  },
  {
    id: "p_americana",
    name: "Americana",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.45,
    points: 0,
    from_position: Position.SIDE_CONTROL_TOP,
    success_position: Position.SIDE_CONTROL_TOP,
    fail_position: Position.GUARD_TOP,
    rarity: MoveRarity.UNCOMMON,
    sub_chance: 0.30,
  },

  // === SIDE CONTROL BOTTOM ===
  {
    id: "p_side_escape",
    name: "Hip Escape",
    type: MoveType.DEF,
    stat: "escapes",
    base_chance: 0.45,
    points: 0,
    from_position: Position.SIDE_CONTROL_BOTTOM,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.SIDE_CONTROL_BOTTOM,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "p_underhook_escape",
    name: "Underhook Escape",
    type: MoveType.TRN,
    stat: "escapes",
    base_chance: 0.40,
    points: 0,
    from_position: Position.SIDE_CONTROL_BOTTOM,
    success_position: Position.HALF_GUARD_BOTTOM,
    fail_position: Position.SIDE_CONTROL_BOTTOM,
    rarity: MoveRarity.COMMON,
  },

  // === MOUNT TOP ===
  {
    id: "p_mounted_armbar",
    name: "Mounted Armbar",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.50,
    points: 0,
    from_position: Position.MOUNT_TOP,
    success_position: Position.MOUNT_TOP,
    fail_position: Position.GUARD_TOP,
    rarity: MoveRarity.RARE,
    sub_chance: 0.45,
  },
  {
    id: "p_back_take_mount",
    name: "Take the Back",
    type: MoveType.TRN,
    stat: "passing",
    base_chance: 0.45,
    points: 4,
    from_position: Position.MOUNT_TOP,
    success_position: Position.BACK_CONTROL,
    fail_position: Position.MOUNT_TOP,
    rarity: MoveRarity.RARE,
  },

  // === MOUNT BOTTOM ===
  {
    id: "p_mount_bridge",
    name: "Bridge Escape",
    type: MoveType.DEF,
    stat: "escapes",
    base_chance: 0.40,
    points: 0,
    from_position: Position.MOUNT_BOTTOM,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.MOUNT_BOTTOM,
    rarity: MoveRarity.COMMON,
  },

  // === BACK CONTROL ===
  {
    id: "p_rnc",
    name: "Rear Naked Choke",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.55,
    points: 0,
    from_position: Position.BACK_CONTROL,
    success_position: Position.BACK_CONTROL,
    fail_position: Position.TURTLE_TOP,
    rarity: MoveRarity.LEGENDARY,
    sub_chance: 0.55,
  },

  // === BACK EXPOSED ===
  {
    id: "p_back_escape",
    name: "Escape Back Control",
    type: MoveType.DEF,
    stat: "escapes",
    base_chance: 0.40,
    points: 0,
    from_position: Position.BACK_EXPOSED,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.BACK_EXPOSED,
    rarity: MoveRarity.COMMON,
  },

  // === TURTLE TOP ===
  {
    id: "p_turtle_back_take",
    name: "Back Take from Turtle",
    type: MoveType.TRN,
    stat: "passing",
    base_chance: 0.55,
    points: 4,
    from_position: Position.TURTLE_TOP,
    success_position: Position.BACK_CONTROL,
    fail_position: Position.TURTLE_TOP,
    rarity: MoveRarity.UNCOMMON,
  },

  // === TURTLE BOTTOM ===
  {
    id: "p_turtle_sit_out",
    name: "Sit Out",
    type: MoveType.DEF,
    stat: "wrestling",
    base_chance: 0.50,
    points: 0,
    from_position: Position.TURTLE_BOTTOM,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.TURTLE_BOTTOM,
    rarity: MoveRarity.COMMON,
  },

  // === FRONT HEADLOCK ATTACK ===
  {
    id: "p_guillotine",
    name: "Guillotine",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.50,
    points: 0,
    from_position: Position.FRONT_HEADLOCK_ATTACK,
    success_position: Position.FRONT_HEADLOCK_ATTACK,
    fail_position: Position.GUARD_TOP,
    rarity: MoveRarity.EPIC,
    sub_chance: 0.40,
  },
  {
    id: "p_snap_down",
    name: "Snap Down",
    type: MoveType.ATK,
    stat: "wrestling",
    base_chance: 0.55,
    points: 2,
    from_position: Position.FRONT_HEADLOCK_ATTACK,
    success_position: Position.TURTLE_TOP,
    fail_position: Position.STANDING,
    rarity: MoveRarity.COMMON,
  },

  // === FRONT HEADLOCK DEFEND ===
  {
    id: "p_fl_defend",
    name: "Posture Up",
    type: MoveType.DEF,
    stat: "wrestling",
    base_chance: 0.55,
    points: 0,
    from_position: Position.FRONT_HEADLOCK_DEFEND,
    success_position: Position.STANDING,
    fail_position: Position.FRONT_HEADLOCK_DEFEND,
    rarity: MoveRarity.COMMON,
  },

  // === SINGLE LEG X OFFENSE ===
  {
    id: "p_slx_sweep",
    name: "SLX Sweep",
    type: MoveType.ATK,
    stat: "leg_entanglements",
    base_chance: 0.50,
    points: 2,
    from_position: Position.SINGLE_LEG_X_OFFENSE,
    success_position: Position.SADDLE_OFFENSE,
    fail_position: Position.SINGLE_LEG_X_OFFENSE,
    rarity: MoveRarity.UNCOMMON,
  },

  // === SINGLE LEG X DEFENSE ===
  {
    id: "p_slx_defend",
    name: "Disengage Legs",
    type: MoveType.DEF,
    stat: "leg_entanglements",
    base_chance: 0.55,
    points: 0,
    from_position: Position.SINGLE_LEG_X_DEFENSE,
    success_position: Position.STANDING,
    fail_position: Position.SINGLE_LEG_X_DEFENSE,
    rarity: MoveRarity.COMMON,
  },

  // === SADDLE OFFENSE ===
  {
    id: "p_heel_hook",
    name: "Heel Hook",
    type: MoveType.SUB,
    stat: "leg_entanglements",
    base_chance: 0.50,
    points: 0,
    from_position: Position.SADDLE_OFFENSE,
    success_position: Position.SADDLE_OFFENSE,
    fail_position: Position.GUARD_BOTTOM,
    rarity: MoveRarity.LEGENDARY,
    sub_chance: 0.50,
  },

  // === SADDLE DEFENSE ===
  {
    id: "p_saddle_escape",
    name: "Clear Knee Line",
    type: MoveType.DEF,
    stat: "leg_entanglements",
    base_chance: 0.45,
    points: 0,
    from_position: Position.SADDLE_DEFENSE,
    success_position: Position.STANDING,
    fail_position: Position.SADDLE_DEFENSE,
    rarity: MoveRarity.UNCOMMON,
  },
];

// ─── Opponent Moves (~20, no legendary) ───

export const OPPONENT_MOVES: Move[] = [
  // === STANDING ===
  {
    id: "o_blast_double",
    name: "Blast Double",
    type: MoveType.ATK,
    stat: "wrestling",
    base_chance: 0.60,
    points: 2,
    from_position: Position.STANDING,
    success_position: Position.GUARD_TOP,
    fail_position: Position.STANDING,
    rarity: MoveRarity.UNCOMMON,
  },
  {
    id: "o_sprawl",
    name: "Sprawl",
    type: MoveType.DEF,
    stat: "wrestling",
    base_chance: 0.65,
    points: 0,
    from_position: Position.STANDING,
    success_position: Position.FRONT_HEADLOCK_ATTACK,
    fail_position: Position.STANDING,
    rarity: MoveRarity.COMMON,
  },

  // === GUARD TOP ===
  {
    id: "o_pressure_pass",
    name: "Pressure Pass",
    type: MoveType.ATK,
    stat: "passing",
    base_chance: 0.55,
    points: 3,
    from_position: Position.GUARD_TOP,
    success_position: Position.SIDE_CONTROL_TOP,
    fail_position: Position.GUARD_TOP,
    rarity: MoveRarity.UNCOMMON,
  },

  // === GUARD BOTTOM ===
  {
    id: "o_scissor_sweep",
    name: "Scissor Sweep",
    type: MoveType.ATK,
    stat: "guard",
    base_chance: 0.45,
    points: 2,
    from_position: Position.GUARD_BOTTOM,
    success_position: Position.MOUNT_TOP,
    fail_position: Position.GUARD_BOTTOM,
    rarity: MoveRarity.COMMON,
  },
  {
    id: "o_guard_retain",
    name: "Retain Guard",
    type: MoveType.DEF,
    stat: "guard",
    base_chance: 0.65,
    points: 0,
    from_position: Position.GUARD_BOTTOM,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.HALF_GUARD_BOTTOM,
    rarity: MoveRarity.COMMON,
  },

  // === HALF GUARD TOP ===
  {
    id: "o_half_smash",
    name: "Smash Pass",
    type: MoveType.ATK,
    stat: "strength",
    base_chance: 0.55,
    points: 3,
    from_position: Position.HALF_GUARD_TOP,
    success_position: Position.SIDE_CONTROL_TOP,
    fail_position: Position.HALF_GUARD_TOP,
    rarity: MoveRarity.UNCOMMON,
  },

  // === HALF GUARD BOTTOM ===
  {
    id: "o_hg_recover",
    name: "Recover Guard",
    type: MoveType.DEF,
    stat: "guard",
    base_chance: 0.55,
    points: 0,
    from_position: Position.HALF_GUARD_BOTTOM,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.HALF_GUARD_BOTTOM,
    rarity: MoveRarity.COMMON,
  },

  // === SIDE CONTROL TOP ===
  {
    id: "o_knee_on_belly",
    name: "Knee on Belly",
    type: MoveType.ATK,
    stat: "passing",
    base_chance: 0.55,
    points: 2,
    from_position: Position.SIDE_CONTROL_TOP,
    success_position: Position.MOUNT_TOP,
    fail_position: Position.SIDE_CONTROL_TOP,
    rarity: MoveRarity.UNCOMMON,
  },
  {
    id: "o_kimura_sc",
    name: "Kimura",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.45,
    points: 0,
    from_position: Position.SIDE_CONTROL_TOP,
    success_position: Position.SIDE_CONTROL_TOP,
    fail_position: Position.GUARD_TOP,
    rarity: MoveRarity.RARE,
    sub_chance: 0.30,
  },

  // === SIDE CONTROL BOTTOM ===
  {
    id: "o_frame_escape",
    name: "Frame Escape",
    type: MoveType.DEF,
    stat: "escapes",
    base_chance: 0.45,
    points: 0,
    from_position: Position.SIDE_CONTROL_BOTTOM,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.SIDE_CONTROL_BOTTOM,
    rarity: MoveRarity.COMMON,
  },

  // === MOUNT TOP ===
  {
    id: "o_cross_choke",
    name: "Cross Choke",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.45,
    points: 0,
    from_position: Position.MOUNT_TOP,
    success_position: Position.MOUNT_TOP,
    fail_position: Position.GUARD_TOP,
    rarity: MoveRarity.RARE,
    sub_chance: 0.35,
  },

  // === MOUNT BOTTOM ===
  {
    id: "o_upa_escape",
    name: "Upa Escape",
    type: MoveType.DEF,
    stat: "escapes",
    base_chance: 0.40,
    points: 0,
    from_position: Position.MOUNT_BOTTOM,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.MOUNT_BOTTOM,
    rarity: MoveRarity.COMMON,
  },

  // === BACK CONTROL ===
  {
    id: "o_rnc",
    name: "Rear Naked Choke",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.50,
    points: 0,
    from_position: Position.BACK_CONTROL,
    success_position: Position.BACK_CONTROL,
    fail_position: Position.TURTLE_TOP,
    rarity: MoveRarity.EPIC,
    sub_chance: 0.45,
  },

  // === BACK EXPOSED ===
  {
    id: "o_turtle_up",
    name: "Turtle Up",
    type: MoveType.DEF,
    stat: "escapes",
    base_chance: 0.45,
    points: 0,
    from_position: Position.BACK_EXPOSED,
    success_position: Position.TURTLE_BOTTOM,
    fail_position: Position.BACK_EXPOSED,
    rarity: MoveRarity.COMMON,
  },

  // === TURTLE TOP ===
  {
    id: "o_clock_choke",
    name: "Clock Choke",
    type: MoveType.ATK,
    stat: "passing",
    base_chance: 0.50,
    points: 2,
    from_position: Position.TURTLE_TOP,
    success_position: Position.BACK_CONTROL,
    fail_position: Position.TURTLE_TOP,
    rarity: MoveRarity.UNCOMMON,
  },

  // === TURTLE BOTTOM ===
  {
    id: "o_granby_roll",
    name: "Granby Roll",
    type: MoveType.DEF,
    stat: "wrestling",
    base_chance: 0.50,
    points: 0,
    from_position: Position.TURTLE_BOTTOM,
    success_position: Position.GUARD_BOTTOM,
    fail_position: Position.TURTLE_BOTTOM,
    rarity: MoveRarity.COMMON,
  },

  // === FRONT HEADLOCK ATTACK ===
  {
    id: "o_darce",
    name: "D'Arce Choke",
    type: MoveType.SUB,
    stat: "submissions",
    base_chance: 0.45,
    points: 0,
    from_position: Position.FRONT_HEADLOCK_ATTACK,
    success_position: Position.FRONT_HEADLOCK_ATTACK,
    fail_position: Position.GUARD_TOP,
    rarity: MoveRarity.RARE,
    sub_chance: 0.35,
  },

  // === FRONT HEADLOCK DEFEND ===
  {
    id: "o_fl_escape",
    name: "Posture Up",
    type: MoveType.DEF,
    stat: "wrestling",
    base_chance: 0.55,
    points: 0,
    from_position: Position.FRONT_HEADLOCK_DEFEND,
    success_position: Position.STANDING,
    fail_position: Position.FRONT_HEADLOCK_DEFEND,
    rarity: MoveRarity.COMMON,
  },

  // === SLX OFFENSE ===
  {
    id: "o_slx_heel_hook",
    name: "Heel Hook Entry",
    type: MoveType.TRN,
    stat: "leg_entanglements",
    base_chance: 0.45,
    points: 0,
    from_position: Position.SINGLE_LEG_X_OFFENSE,
    success_position: Position.SADDLE_OFFENSE,
    fail_position: Position.SINGLE_LEG_X_OFFENSE,
    rarity: MoveRarity.UNCOMMON,
  },

  // === SLX DEFENSE ===
  {
    id: "o_slx_clear",
    name: "Clear Legs",
    type: MoveType.DEF,
    stat: "leg_entanglements",
    base_chance: 0.55,
    points: 0,
    from_position: Position.SINGLE_LEG_X_DEFENSE,
    success_position: Position.STANDING,
    fail_position: Position.SINGLE_LEG_X_DEFENSE,
    rarity: MoveRarity.COMMON,
  },

  // === SADDLE OFFENSE ===
  {
    id: "o_straight_ankle",
    name: "Straight Ankle Lock",
    type: MoveType.SUB,
    stat: "leg_entanglements",
    base_chance: 0.45,
    points: 0,
    from_position: Position.SADDLE_OFFENSE,
    success_position: Position.SADDLE_OFFENSE,
    fail_position: Position.GUARD_BOTTOM,
    rarity: MoveRarity.RARE,
    sub_chance: 0.35,
  },

  // === SADDLE DEFENSE ===
  {
    id: "o_saddle_escape",
    name: "Boot Scoot",
    type: MoveType.DEF,
    stat: "leg_entanglements",
    base_chance: 0.45,
    points: 0,
    from_position: Position.SADDLE_DEFENSE,
    success_position: Position.STANDING,
    fail_position: Position.SADDLE_DEFENSE,
    rarity: MoveRarity.COMMON,
  },
];
